# Generated by Django 3.1.2 on 2020-10-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_numberrange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberrange',
            old_name='number',
            new_name='numbers',
        ),
    ]
