# Generated by Django 3.1.2 on 2020-10-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201027_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='first_name',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='last_name',
        ),
    ]
