# Generated by Django 3.1.2 on 2020-10-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
