# Generated by Django 3.1.2 on 2020-10-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_life_numberrange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberrange',
            name='id',
        ),
        migrations.AlterField(
            model_name='numberrange',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
