# Generated by Django 3.1.2 on 2020-10-28 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201027_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life',
            name='number',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
