# Generated by Django 3.1.2 on 2020-10-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201028_0628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumberRange',
        ),
    ]
