# Generated by Django 3.1.2 on 2020-10-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_numberrange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='life',
            name='number',
        ),
    ]
