# Generated by Django 3.1.2 on 2020-10-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_life_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Life',
        ),
    ]
