# Generated by Django 3.1.2 on 2020-10-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life',
            name='number',
            field=models.IntegerField(),
        ),
    ]
